language: c++

branches:
  except:
    - automatic

cache:
  directories:
    - download

matrix:
  include:
    - os: linux
      dist: bionic
      env:
        - _BUILD=win32
        - _MINGW=mingw32
        - _HOST=i686-w64-mingw32
      before_install:
        - docker pull archlinux
      install:
        - container=$(docker run -d -i -t -v /home:/home archlinux /bin/bash)
        - |
          cross() {
            docker exec -w "$(pwd)" -e "_BUILD=$_BUILD" -e "_MINGW=$_MINGW" -e "_HOST=$_HOST" -i -t "$container" "$@"
          }
      script:
        - cross bash .travis/script-mingw.sh
        - cp -drfv bin regrader-"$_BUILD"
        - rm -f regrader-"$_BUILD"/README
        - install -d release
        - zip -9 -r release/regrader-"$_BUILD".zip regrader-"$_BUILD"
    - os: linux
      dist: bionic
      env:
        - _BUILD=win64
        - _MINGW=mingw64
        - _HOST=x86_64-w64-mingw32
      before_install:
        - docker pull archlinux
      install:
        - container=$(docker run -d -i -t -v /home:/home archlinux /bin/bash)
        - |
          cross() {
            docker exec -w "$(pwd)" -e "_BUILD=$_BUILD" -e "_MINGW=$_MINGW" -e "_HOST=$_HOST" -i -t "$container" "$@"
          }
      script:
        - cross bash .travis/script-mingw.sh
        - cp -drfv bin regrader-"$_BUILD"
        - rm -f regrader-"$_BUILD"/README
        - install -d release
        - zip -9 -r release/regrader-"$_BUILD".zip regrader-"$_BUILD"
    - os: osx
      osx_image: xcode9.2
      env:
        - _BUILD=macos
      script:
        - bash .travis/script-macos.sh
        - cp -av bin regrader-"$_BUILD"
        - rm -f regrader-"$_BUILD"/README
        - install -d release
        - zip -9 -r release/regrader-"$_BUILD".zip regrader-"$_BUILD"
    - os: linux
      dist: trusty
      env:
        - _BITS=64
        - _BUILD=linux64
      before_install:
        - sudo apt-get update -qq
      install:
        - sudo apt-get install checkinstall libcairo2-dev python
      script:
        - bash .travis/script-linux.sh
        - cp -drfv bin regrader-"$_BUILD"
        - rm -f regrader-"$_BUILD"/README
        - install -d release
        - zip -9 -r release/regrader-"$_BUILD".zip regrader-"$_BUILD"
        - echo "A delay effect where the repeats degrade in resolution" > description-pak
        - sudo checkinstall --type=debian --install=no --default --pkgname=regrader --pkgversion="`git describe --abbrev=0 | sed 's/^v//'``git log -n 1 --pretty=format:"+%cd~git%h" --date=short master | sed 's/-//g'`" --pkgarch=amd64 --pkgrelease=0jpc1 --pkglicense=BSL-1.0 --pkggroup=sound --maintainer="jp-dev@inbox.ru" --nodoc
        - sudo mv -f *.deb release/regrader-"$_BUILD".deb

before_script:
  - sed -i~ 's%/usr/local%/usr%g' plugins/*/Makefile

before_deploy:
  - |
    if test "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false"; then
      export TRAVIS_TAG=automatic
      git tag -f "$TRAVIS_TAG"
    fi

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: release/*
  file_glob: true
  prerelease: true
  overwrite: true
  skip_cleanup: true
  on:
    branch: master

env:
  global:
    secure: "ekhpEcbeQa58ETkjVoa9kcVjAphPr+a+MM5OSROrYskgwiikDQiUKURb2BySukfh9IfiyX/crFcwfR5isCbF8IT6SCGrFwy5FbLWyGPwGbs1CIxOwyLGraN7eb5KSBYSKbIivu82zCk7BjPUcIbodoZcod0xNCV0m5BauriiZM/w0hLwe+dnRx2SJJirHZKK2MQAma9ixG6qCxCvDKcK1mQppb+TZOueP2L2uUpeI15qL9t+MPdo3/hL4GqLnZ1oBuTUlYq9+28znEU2VLwkaxqlvsIxKkY8BfkA8ZjZzqs86dy8CBevkIJUGB3pZOKjirCV1w6Oh7yBof99dGmdobcBuY5/rupN50FwfKqwSXh53oHImo1xWSYB8PNmXuj5j7OniajKXtdueGNZZy8SPF78ZL1Q7VIpONxHykclt0IUscypoiTOrpSvWbWPuvbPLWKaD3t5/xETB/wq7yxifsN6tI4Kj5veExISrHxJs5x/M8qrtpoiPexnqwfQF6VFQrtd7yjSHg9BJOUaCa+orZHDuBOiyPgswP+ZmCwLk300V4jcH6ieVF9mPcxj7rebxT+TW8Kf5K6eqE8l4Rp4ReN+z+001qk+XXWQ8MxazR7BlAgKsVZX8MuSJUGRO2lab5LNku9CfpzFex6oqwrf2z5RQSBclFmw0NNB/Pm+4rM="

notifications:
  irc:
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    channels:
      - "ircs://chat.freenode.net:7070/#librazik"
